export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { email, firstName, lastName } = req.body;

  if (!email || !firstName) {
    return res.status(400).json({ error: 'Missing required fields' });
  }

  const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbxCdjyhCtdmHHIqa4Ex_T2l6NUD6FswDUta4UrBNYIX7DLvr_R7-DnmpPOVQ4_j4FK0/exec';

  try {
    await fetch(SCRIPT_URL, {
      method: 'POST',
      mode: 'no-cors',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type: 'name', email, firstName, lastName })
    });
  } catch(err) {}

  try {
    const resendRes = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.RESEND_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'Peak 65 <noreply@getpeak65.com>',
        to: email,
        subject: "You're on the list.",
        html: `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/></head>
<body style="margin:0;padding:0;background:#080808;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#080808;padding:48px 20px;">
    <tr><td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;">
        <tr><td style="padding-bottom:40px;">
          <p style="margin:0;font-size:13px;font-weight:900;letter-spacing:0.22em;text-transform:uppercase;color:#e8ff47;">PEAK 65</p>
        </td></tr>
        <tr><td style="padding-bottom:32px;border-bottom:0.5px solid rgba(255,255,255,0.08);">
          <h1 style="margin:0 0 20px;font-size:42px;font-weight:900;text-transform:uppercase;line-height:0.9;color:#f0ede8;letter-spacing:-0.01em;">Hey ${firstName},<br>You're in.</h1>
          <p style="margin:0;font-size:16px;color:#8a877f;line-height:1.7;">You're on the Peak 65 waitlist. Here's what you're getting access to:</p>
        </td></tr>
        <tr><td style="padding:32px 0;border-bottom:0.5px solid rgba(255,255,255,0.08);">
          <table width="100%" cellpadding="0" cellspacing="0">
            <tr><td style="padding-bottom:24px;">
              <p style="margin:0 0 6px;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#e8ff47;">01 — AI Training</p>
              <p style="margin:0;font-size:15px;color:#8a877f;line-height:1.65;">Your program is generated by AI and built around your goal, your schedule, and your body. Not a template. Not a guess.</p>
            </td></tr>
            <tr><td style="padding-bottom:24px;">
              <p style="margin:0 0 6px;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#e8ff47;">02 — Assessment Week</p>
              <p style="margin:0;font-size:15px;color:#8a877f;line-height:1.65;">Week one starts with an assessment — a short series of efforts that tells us exactly where you are, so every session after it is built around your real data. Not a guess. Not a template.</p>
            </td></tr>
            <tr><td style="padding-bottom:24px;">
              <p style="margin:0 0 6px;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#e8ff47;">03 — Wearable Driven</p>
              <p style="margin:0;font-size:15px;color:#8a877f;line-height:1.65;">Connect Garmin or Amazfit. Your HRV, resting HR, and sleep data adjust your program every single week. The app gets smarter the longer you use it.</p>
            </td></tr>
            <tr><td>
              <p style="margin:0 0 6px;font-size:11px;font-weight:700;letter-spacing:0.12em;text-transform:uppercase;color:#e8ff47;">04 — Hyrox + General Fitness</p>
              <p style="margin:0;font-size:15px;color:#8a877f;line-height:1.65;">Training for a Hyrox race or just want to run faster, get stronger, and look your best — Peak 65 programs both paths at world-class level.</p>
            </td></tr>
          </table>
        </td></tr>
        <tr><td style="padding-top:32px;">
          <p style="margin:0 0 24px;font-size:15px;color:#8a877f;line-height:1.7;">You'll be first to know when we launch. Founding members get the lowest price we'll ever offer — locked for life.</p>
          <p style="margin:0 0 6px;font-size:15px;color:#8a877f;line-height:1.7;">Follow along for updates.</p>
          <a href="https://instagram.com/getpeak65" style="color:#e8ff47;font-weight:700;text-decoration:none;">@getpeak65</a>
        </td></tr>
        <tr><td style="padding-top:48px;">
          <p style="margin:0;font-size:12px;color:#3a3835;">© 2025 Peak 65 · getpeak65.com · You're receiving this because you joined the waitlist.</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`
      })
    });
  } catch(err) {}

  return res.status(200).json({ success: true });
}
